sum([], 0).
sum([F|Rest], S) :- sum(Rest, S1), S is S1 + F.

filter([], Max, []).
filter([Num|Nums], Max, [Num|Filtered]) :- Num =< Max, filter(Nums, Max, Filtered).
filter([Num|Nums], Max, Filtered) :- Num > Max, filter(Nums, Max, Filtered).

find_total_each_dir([], Processed, []).
find_total_each_dir([Dir|Dirs], Processed, [First|Result]) :-
    length(Dirs, L), write(L), nl,
    find_total_one_dir(Dir, Processed, First),
    find_total_each_dir(Dirs, Processed, Result).

find_total_one_dir(Dir, [], 0).
find_total_one_dir(Dir, [[P, T]|Processed], Total) :-
    append(X, Dir, P),
    find_total_one_dir(Dir, Processed, TotalRest),
    Total is T + TotalRest.
find_total_one_dir(Dir, [[P, T]|Processed], Total) :-
    \+ append(X, Dir, P),
    find_total_one_dir(Dir, Processed, Total).


all_dirs([], Acc, Acc).
all_dirs([First|Processed], Acc, Result) :- append([D], RestInfo, First), \+ member(D, Acc), all_dirs(Processed, [D|Acc], Result).
all_dirs([First|Processed], Acc, Result) :- append([D], RestInfo, First), member(D, Acc), all_dirs(Processed, Acc, Result).

process([], Current, P, [Current|P]).
process([L|Lines], [[C|Current], Total], Paths, P) :-
    arg(1, L, cd),
    arg(2, L, ".."),
    append(X, [[[C|Current], T]|Rest], Paths),
    UpdatedTotal is T + Total,
    append(X, [[[C|Current], UpdatedTotal]|Rest], NewPaths),
    process(Lines, [Current, T], NewPaths, P). 

process([L|Lines], [[C|Current], Total], Paths, P) :-
    arg(1, L, cd),
    arg(2, L, ".."),
    \+ append(X, [[[C|Current], T]|Rest], Paths),
    append([[[C|Current], Total]], Paths, NewPaths),
    process(Lines, [Current, 0], NewPaths, P). 

process([L|Lines], [Current, Total], Paths, P) :-
    arg(1, L, cd),
    arg(2, L, Dir),
    Dir \= "..",
    append([Dir], Current, NewCurrent),
    append([[Current, Total]], Paths, NewPaths),
    process(Lines, [NewCurrent, 0], NewPaths, P).

process([L|Lines], Current, Paths, P) :-
    arg(1, L, cd),
    arg(2, L, Dir),
    Dir = "/",
    process(Lines, [["/"], 0], [], P).

process([L|Lines], Current, Paths, P) :- arg(1, L, ls), process(Lines, Current, Paths, P).

process([L|Lines], Current, Paths, P) :-
    arg(1, L, dir),
    process(Lines, Current, Paths, P).

process([L|Lines], [Current, Total], Paths, P) :-
    arg(1, L, X),
    integer(X),
    NewTotal is Total + X,
    process(Lines, [Current, NewTotal], Paths, P).

input([
line(cd, "/"),
line(ls),
line(dir, "bsncwlw"),
line(dir, "dssnr"),
line(290062, "lpj.tpq"),
line(183564, "rfhsnp.mfv"),
line(dir, "sfb"),
line(199911, "ttctlvjp"),
line(dir, "vhbnn"),
line(253955, "vngjfb.nlm"),
line(284563, "vzgpzlv.hgm"),
line(cd, "bsncwlw"),
line(ls),
line(264332, "gzsrhr.snp"),
line(94633, "ttctlvjp"),
line(cd, ".."),
line(cd, "dssnr"),
line(ls),
line(101990, "vmqbwtd.dqv"),
line(cd, ".."),
line(cd, "sfb"),
line(ls),
line(dir, "dth"),
line(dir, "gmgwq"),
line(dir, "hmvtj"),
line(dir, "jrcgrvp"),
line(dir, "mjqww"),
line(234348, "nrrtpbqw"),
line(dir, "ntczgz"),
line(dir, "qvfnt"),
line(dir, "tvmv"),
line(dir, "vrsdff"),
line(dir, "wndttgwm"),
line(cd, "dth"),
line(ls),
line(214526, "btvzp"),
line(cd, ".."),
line(cd, "gmgwq"),
line(ls),
line(270924, "czj.rsc"),
line(dir, "lfnhb"),
line(97804, "snqqrvwd.hbq"),
line(99847, "tjcpgqnm.dvv"),
line(cd, "lfnhb"),
line(ls),
line(110202, "cvffv.wzr"),
line(45842, "lfnhb"),
line(181410, "mjqww.zhl"),
line(72379, "snqqrvwd.tsb"),
line(46957, "vdjjgd.lnb"),
line(dir, "vrsdff"),
line(cd, "vrsdff"),
line(ls),
line(191477, "jrcgrvp.plv"),
line(292376, "mjqww"),
line(97997, "vdjjgd.lnb"),
line(5027, "zplw.cmd"),
line(cd, ".."),
line(cd, ".."),
line(cd, ".."),
line(cd, "hmvtj"),
line(ls),
line(dir, "dqvjbhg"),
line(cd, "dqvjbhg"),
line(ls),
line(98579, "vdjjgd.lnb"),
line(cd, ".."),
line(cd, ".."),
line(cd, "jrcgrvp"),
line(ls),
line(dir, "dzrcrcz"),
line(3233, "lfnhb.frn"),
line(dir, "sln"),
line(dir, "sqtj"),
line(268936, "ttctlvjp"),
line(dir, "tzqsbwnb"),
line(cd, "dzrcrcz"),
line(ls),
line(218954, "bppp.qfg"),
line(206406, "zwhtbhg.jms"),
line(cd, ".."),
line(cd, "sln"),
line(ls),
line(269167, "fvsc"),
line(274943, "mjtb.gpd"),
line(cd, ".."),
line(cd, "sqtj"),
line(ls),
line(dir, "cvjwqpz"),
line(dir, "djqjv"),
line(11761, "frrdhnsz.ltt"),
line(dir, "htc"),
line(dir, "lfnhb"),
line(dir, "mcfdlh"),
line(dir, "mjqww"),
line(cd, "cvjwqpz"),
line(ls),
line(46716, "fpd.ljl"),
line(cd, ".."),
line(cd, "djqjv"),
line(ls),
line(dir, "gplnb"),
line(282457, "jgbn.zhm"),
line(dir, "jrcgrvp"),
line(dir, "lfnhb"),
line(cd, "gplnb"),
line(ls),
line(dir, "gqrlz"),
line(dir, "srpcmhq"),
line(dir, "vrsdff"),
line(cd, "gqrlz"),
line(ls),
line(43021, "pmshlv"),
line(124139, "vrsdff"),
line(255316, "zpgwmgf"),
line(cd, ".."),
line(cd, "srpcmhq"),
line(ls),
line(128669, "jrcgrvp"),
line(dir, "lfnhb"),
line(243510, "vrsdff.pgt"),
line(134902, "vzmfbcv.pbc"),
line(dir, "znfw"),
line(cd, "lfnhb"),
line(ls),
line(150844, "lfnhb"),
line(202341, "vngjfb.nlm"),
line(cd, ".."),
line(cd, "znfw"),
line(ls),
line(dir, "cdnh"),
line(dir, "ctpslqg"),
line(dir, "jrcgrvp"),
line(dir, "tmjnj"),
line(dir, "ttfczgwn"),
line(cd, "cdnh"),
line(ls),
line(83983, "bhlmzppw.gzp"),
line(dir, "fdvcmbt"),
line(14625, "fphdhzbw.fnf"),
line(dir, "ndbztbq"),
line(217778, "rzvzpn.gzv"),
line(cd, "fdvcmbt"),
line(ls),
line(dir, "hzgmnswh"),
line(dir, "wtt"),
line(cd, "hzgmnswh"),
line(ls),
line(dir, "wshrmd"),
line(cd, "wshrmd"),
line(ls),
line(314723, "vrsdff.rtc"),
line(cd, ".."),
line(cd, ".."),
line(cd, "wtt"),
line(ls),
line(32262, "tqsvdvfp.ggd"),
line(cd, ".."),
line(cd, ".."),
line(cd, "ndbztbq"),
line(ls),
line(91717, "sgvn.rss"),
line(cd, ".."),
line(cd, ".."),
line(cd, "ctpslqg"),
line(ls),
line(249954, "hnpc.cht"),
line(119625, "vdjjgd.lnb"),
line(cd, ".."),
line(cd, "jrcgrvp"),
line(ls),
line(dir, "lfnhb"),
line(dir, "prrhq"),
line(cd, "lfnhb"),
line(ls),
line(115317, "ncdpc.mvm"),
line(cd, ".."),
line(cd, "prrhq"),
line(ls),
line(78208, "mjqww.mhs"),
line(280559, "qqhtc.tmr"),
line(275434, "ttctlvjp"),
line(cd, ".."),
line(cd, ".."),
line(cd, "tmjnj"),
line(ls),
line(20439, "cgvctg.sqm"),
line(69239, "ftlrq.pll"),
line(127427, "gwgpwlg.dhd"),
line(dir, "snqqrvwd"),
line(dir, "vbqdpjp"),
line(cd, "snqqrvwd"),
line(ls),
line(27706, "mjsgdblr"),
line(64740, "vdjjgd.lnb"),
line(cd, ".."),
line(cd, "vbqdpjp"),
line(ls),
line(dir, "pchgrt"),
line(cd, "pchgrt"),
line(ls),
line(59640, "hmtsjzf"),
line(cd, ".."),
line(cd, ".."),
line(cd, ".."),
line(cd, "ttfczgwn"),
line(ls),
line(85314, "pmshlv"),
line(cd, ".."),
line(cd, ".."),
line(cd, ".."),
line(cd, "vrsdff"),
line(ls),
line(315614, "jrcgrvp.vgn"),
line(cd, ".."),
line(cd, ".."),
line(cd, "jrcgrvp"),
line(ls),
line(184058, "wqmmcclb"),
line(cd, ".."),
line(cd, "lfnhb"),
line(ls),
line(201903, "cplb"),
line(79091, "jgbn.zhm"),
line(1778, "tpjq.qpr"),
line(62410, "wtvwvw.gwf"),
line(cd, ".."),
line(cd, ".."),
line(cd, "htc"),
line(ls),
line(dir, "hhlvws"),
line(229278, "jrcgrvp.phz"),
line(dir, "njh"),
line(cd, "hhlvws"),
line(ls),
line(174639, "lfnhb.wbt"),
line(174488, "qrjsccz.mbm"),
line(107151, "vrz.ctn"),
line(cd, ".."),
line(cd, "njh"),
line(ls),
line(dir, "vzhhrvqj"),
line(cd, "vzhhrvqj"),
line(ls),
line(154428, "rnhn.nwm"),
line(cd, ".."),
line(cd, ".."),
line(cd, ".."),
line(cd, "lfnhb"),
line(ls),
line(230816, "mmq.fqh"),
line(dir, "nbwtcrpl"),
line(dir, "rlz"),
line(62597, "rnmdwrw.ljf"),
line(552, "rtw"),
line(232443, "vdjjgd.lnb"),
line(dir, "vgvq"),
line(cd, "nbwtcrpl"),
line(ls),
line(dir, "ftflrgzj"),
line(86404, "mjqww.zqd"),
line(159575, "mwpd.gwc"),
line(dir, "nsjfj"),
line(dir, "pfg"),
line(cd, "ftflrgzj"),
line(ls),
line(dir, "glpnz"),
line(282475, "vrsdff.ppc"),
line(cd, "glpnz"),
line(ls),
line(dir, "cdw"),
line(dir, "hjntz"),
line(dir, "jdszmcd"),
line(250018, "mjqww.gdv"),
line(cd, "cdw"),
line(ls),
line(164522, "jgbn.zhm"),
line(93952, "jhdbcd.swb"),
line(cd, ".."),
line(cd, "hjntz"),
line(ls),
line(257626, "vdjjgd.lnb"),
line(cd, ".."),
line(cd, "jdszmcd"),
line(ls),
line(dir, "lfnhb"),
line(dir, "nwmjhbt"),
line(cd, "lfnhb"),
line(ls),
line(144608, "jrcgrvp"),
line(cd, ".."),
line(cd, "nwmjhbt"),
line(ls),
line(81512, "cnlwmv.pvq"),
line(cd, ".."),
line(cd, ".."),
line(cd, ".."),
line(cd, ".."),
line(cd, "nsjfj"),
line(ls),
line(158675, "shsgq"),
line(cd, ".."),
line(cd, "pfg"),
line(ls),
line(98277, "lfnhb.tjc"),
line(dir, "snqqrvwd"),
line(170691, "vtmmz"),
line(cd, "snqqrvwd"),
line(ls),
line(121715, "ffr.zpv"),
line(105094, "jgbn.zhm"),
line(cd, ".."),
line(cd, ".."),
line(cd, ".."),
line(cd, "rlz"),
line(ls),
line(247967, "bmlqhfnm"),
line(270713, "mtg"),
line(207128, "wvblbnz"),
line(cd, ".."),
line(cd, "vgvq"),
line(ls),
line(209343, "jrcgrvp"),
line(cd, ".."),
line(cd, ".."),
line(cd, "mcfdlh"),
line(ls),
line(15958, "pbtp.pmh"),
line(cd, ".."),
line(cd, "mjqww"),
line(ls),
line(dir, "jrcgrvp"),
line(dir, "lfnhb"),
line(55522, "pmshlv"),
line(dir, "qvmhbp"),
line(dir, "zldldv"),
line(cd, "jrcgrvp"),
line(ls),
line(189839, "jrcgrvp"),
line(73108, "pdzcm.gqm"),
line(cd, ".."),
line(cd, "lfnhb"),
line(ls),
line(dir, "fgcmvwd"),
line(42810, "jgbn.zhm"),
line(dir, "jrcgrvp"),
line(dir, "vdpbmtf"),
line(cd, "fgcmvwd"),
line(ls),
line(28530, "mjqww.zdr"),
line(cd, ".."),
line(cd, "jrcgrvp"),
line(ls),
line(5386, "gpgtds.sdh"),
line(cd, ".."),
line(cd, "vdpbmtf"),
line(ls),
line(284528, "crwdp.hhm"),
line(54212, "pmshlv"),
line(cd, ".."),
line(cd, ".."),
line(cd, "qvmhbp"),
line(ls),
line(dir, "jrcgrvp"),
line(dir, "ptlmpl"),
line(dir, "vhql"),
line(160711, "wwt"),
line(cd, "jrcgrvp"),
line(ls),
line(dir, "ndmprm"),
line(254907, "rqzhqpt.dbj"),
line(dir, "tvbrzjrq"),
line(226311, "zjbwrbw"),
line(cd, "ndmprm"),
line(ls),
line(dir, "jqrdvnbp"),
line(dir, "mjqww"),
line(cd, "jqrdvnbp"),
line(ls),
line(299157, "snqqrvwd"),
line(cd, ".."),
line(cd, "mjqww"),
line(ls),
line(dir, "mjqww"),
line(101780, "snqqrvwd.fvp"),
line(cd, "mjqww"),
line(ls),
line(40424, "pmshlv"),
line(cd, ".."),
line(cd, ".."),
line(cd, ".."),
line(cd, "tvbrzjrq"),
line(ls),
line(172207, "bbb.lmg"),
line(dir, "mjqww"),
line(dir, "snqqrvwd"),
line(218707, "ttctlvjp"),
line(289582, "vngjfb.nlm"),
line(cd, "mjqww"),
line(ls),
line(dir, "vrsdff"),
line(cd, "vrsdff"),
line(ls),
line(dir, "dbfqmmvq"),
line(cd, "dbfqmmvq"),
line(ls),
line(19934, "qghnzsv.rgc"),
line(cd, ".."),
line(cd, ".."),
line(cd, ".."),
line(cd, "snqqrvwd"),
line(ls),
line(27161, "vdjjgd.lnb"),
line(cd, ".."),
line(cd, ".."),
line(cd, ".."),
line(cd, "ptlmpl"),
line(ls),
line(235908, "hlwzt"),
line(171817, "mbdsf.lvm"),
line(cd, ".."),
line(cd, "vhql"),
line(ls),
line(167713, "ddzm.qnz"),
line(1725, "ggnccf.sbd"),
line(dir, "gmstw"),
line(229981, "jzp.ldj"),
line(80353, "lfnhb.qzs"),
line(dir, "tnjnlj"),
line(286555, "ttctlvjp"),
line(cd, "gmstw"),
line(ls),
line(299744, "jrcgrvp.lqt"),
line(dir, "jshshg"),
line(dir, "pmjmngss"),
line(145296, "vrsdff"),
line(152354, "vzrwgjpc.msq"),
line(cd, "jshshg"),
line(ls),
line(169710, "jgbn.zhm"),
line(309539, "vnclc"),
line(cd, ".."),
line(cd, "pmjmngss"),
line(ls),
line(305357, "mjqww.qph"),
line(cd, ".."),
line(cd, ".."),
line(cd, "tnjnlj"),
line(ls),
line(dir, "jwtj"),
line(dir, "pghml"),
line(cd, "jwtj"),
line(ls),
line(dir, "jjtbcdpv"),
line(101453, "lfnhb"),
line(dir, "ppvbjrhr"),
line(dir, "tplsqph"),
line(cd, "jjtbcdpv"),
line(ls),
line(247459, "lprglf.pbt"),
line(8862, "wjwf.btb"),
line(cd, ".."),
line(cd, "ppvbjrhr"),
line(ls),
line(83453, "mjplqgvf.bzc"),
line(cd, ".."),
line(cd, "tplsqph"),
line(ls),
line(300026, "nzfjn.plg"),
line(dir, "zwh"),
line(cd, "zwh"),
line(ls),
line(160407, "vngjfb.nlm"),
line(cd, ".."),
line(cd, ".."),
line(cd, ".."),
line(cd, "pghml"),
line(ls),
line(88913, "bpjf.clf"),
line(cd, ".."),
line(cd, ".."),
line(cd, ".."),
line(cd, ".."),
line(cd, "zldldv"),
line(ls),
line(160867, "vngjfb.nlm"),
line(cd, ".."),
line(cd, ".."),
line(cd, ".."),
line(cd, "tzqsbwnb"),
line(ls),
line(dir, "lfnhb"),
line(dir, "stdnrj"),
line(dir, "wgfvcjcf"),
line(dir, "wrtnvm"),
line(cd, "lfnhb"),
line(ls),
line(230926, "wprbvfc.llh"),
line(cd, ".."),
line(cd, "stdnrj"),
line(ls),
line(118152, "nrctwt.hpw"),
line(cd, ".."),
line(cd, "wgfvcjcf"),
line(ls),
line(12672, "bmcscsw.tvj"),
line(cd, ".."),
line(cd, "wrtnvm"),
line(ls),
line(162743, "jgbn.zhm"),
line(cd, ".."),
line(cd, ".."),
line(cd, ".."),
line(cd, "mjqww"),
line(ls),
line(dir, "bqpmsnv"),
line(dir, "cfzqvmlc"),
line(135084, "mjqww.zpw"),
line(63486, "srf"),
line(dir, "tfzbhps"),
line(171527, "vdjjgd.lnb"),
line(dir, "vrsdff"),
line(cd, "bqpmsnv"),
line(ls),
line(90710, "jgbn.zhm"),
line(240953, "plvbfgp.cvp"),
line(cd, ".."),
line(cd, "cfzqvmlc"),
line(ls),
line(dir, "vcfwwlb"),
line(cd, "vcfwwlb"),
line(ls),
line(11321, "vdjjgd.lnb"),
line(cd, ".."),
line(cd, ".."),
line(cd, "tfzbhps"),
line(ls),
line(300432, "brv"),
line(273987, "jrcgrvp"),
line(dir, "mjqww"),
line(dir, "qjsjj"),
line(8449, "rjqrnfct"),
line(dir, "rvm"),
line(dir, "vrsdff"),
line(117697, "zhwbllv.lpj"),
line(cd, "mjqww"),
line(ls),
line(dir, "mjqww"),
line(250614, "mzp"),
line(dir, "rfwwp"),
line(dir, "vrsdff"),
line(89064, "zqzmpqhd.sgm"),
line(cd, "mjqww"),
line(ls),
line(82140, "bqgbbwm"),
line(cd, ".."),
line(cd, "rfwwp"),
line(ls),
line(dir, "cgmzd"),
line(dir, "jrcgrvp"),
line(3536, "njnpg"),
line(40653, "vdjjgd.lnb"),
line(99587, "vngjfb.nlm"),
line(cd, "cgmzd"),
line(ls),
line(75395, "jqnhv.qpl"),
line(218635, "pmshlv"),
line(17021, "vngjfb.nlm"),
line(cd, ".."),
line(cd, "jrcgrvp"),
line(ls),
line(58428, "dhfqqwt.wtn"),
line(196643, "jgbn.zhm"),
line(dir, "snqqrvwd"),
line(309352, "vdjjgd.lnb"),
line(cd, "snqqrvwd"),
line(ls),
line(238675, "dzpvwv.ncp"),
line(69199, "lfnhb.mrb"),
line(cd, ".."),
line(cd, ".."),
line(cd, ".."),
line(cd, "vrsdff"),
line(ls),
line(67256, "jqmss.lhp"),
line(dir, "jrvsrhlf"),
line(101311, "lhbmv.bwl"),
line(cd, "jrvsrhlf"),
line(ls),
line(191305, "snqqrvwd"),
line(cd, ".."),
line(cd, ".."),
line(cd, ".."),
line(cd, "qjsjj"),
line(ls),
line(dir, "bljbhwg"),
line(dir, "fbzg"),
line(73749, "gth.wwq"),
line(dir, "lfnhb"),
line(296698, "lfnhb.ccj"),
line(62939, "mjqww"),
line(dir, "rcltts"),
line(cd, "bljbhwg"),
line(ls),
line(7022, "ttctlvjp"),
line(cd, ".."),
line(cd, "fbzg"),
line(ls),
line(290427, "vlm.wtf"),
line(cd, ".."),
line(cd, "lfnhb"),
line(ls),
line(232147, "hchjd.gvt"),
line(87988, "pbdsbh.mtj"),
line(cd, ".."),
line(cd, "rcltts"),
line(ls),
line(271382, "pmshlv"),
line(dir, "whthc"),
line(cd, "whthc"),
line(ls),
line(248784, "pvltmhwq.hww"),
line(cd, ".."),
line(cd, ".."),
line(cd, ".."),
line(cd, "rvm"),
line(ls),
line(dir, "fgblz"),
line(219799, "tmdlnjw"),
line(280804, "trs"),
line(198792, "ttctlvjp"),
line(103869, "vdjjgd.lnb"),
line(117484, "vngjfb.nlm"),
line(dir, "vrsdff"),
line(cd, "fgblz"),
line(ls),
line(146821, "ftwzjf"),
line(34704, "ttctlvjp"),
line(cd, ".."),
line(cd, "vrsdff"),
line(ls),
line(dir, "jfgdp"),
line(113986, "rslfvqnj"),
line(cd, "jfgdp"),
line(ls),
line(247425, "vdjjgd.lnb"),
line(215872, "vngjfb.nlm"),
line(cd, ".."),
line(cd, ".."),
line(cd, ".."),
line(cd, "vrsdff"),
line(ls),
line(dir, "rlbbqld"),
line(274950, "vrsdff.brz"),
line(190523, "vrsdff.sgs"),
line(cd, "rlbbqld"),
line(ls),
line(dir, "mjqww"),
line(204582, "ttctlvjp"),
line(cd, "mjqww"),
line(ls),
line(dir, "fjpnsv"),
line(293683, "jgbn.zhm"),
line(cd, "fjpnsv"),
line(ls),
line(dir, "gssqhzr"),
line(dir, "tnbrwc"),
line(cd, "gssqhzr"),
line(ls),
line(194501, "rtqjsrh.qbr"),
line(208907, "vdjjgd.lnb"),
line(cd, ".."),
line(cd, "tnbrwc"),
line(ls),
line(301363, "vrsdff.bjs"),
line(cd, ".."),
line(cd, ".."),
line(cd, ".."),
line(cd, ".."),
line(cd, ".."),
line(cd, ".."),
line(cd, "vrsdff"),
line(ls),
line(243129, "tzftr.lnd"),
line(54940, "vszlnw.nnz"),
line(cd, ".."),
line(cd, ".."),
line(cd, "ntczgz"),
line(ls),
line(dir, "brzscmg"),
line(dir, "fzcp"),
line(cd, "brzscmg"),
line(ls),
line(253980, "jsnwqhts"),
line(cd, ".."),
line(cd, "fzcp"),
line(ls),
line(133626, "qpdlplzt.ccr"),
line(cd, ".."),
line(cd, ".."),
line(cd, "qvfnt"),
line(ls),
line(197353, "bnmw"),
line(dir, "glzzbcfr"),
line(dir, "rbw"),
line(278771, "tjsqs.lqr"),
line(258759, "vdjjgd.lnb"),
line(cd, "glzzbcfr"),
line(ls),
line(205953, "jgbn.zhm"),
line(207362, "snqqrvwd"),
line(cd, ".."),
line(cd, "rbw"),
line(ls),
line(164242, "mjqww.lqb"),
line(cd, ".."),
line(cd, ".."),
line(cd, "tvmv"),
line(ls),
line(80194, "lpntbv.phh"),
line(cd, ".."),
line(cd, "vrsdff"),
line(ls),
line(dir, "bgmfwb"),
line(dir, "dvqtdsr"),
line(118820, "jrcgrvp.nsr"),
line(dir, "pggh"),
line(132530, "stj.ldg"),
line(3436, "vwpdb.gmf"),
line(dir, "zlzjmjvn"),
line(cd, "bgmfwb"),
line(ls),
line(dir, "bqzdswtj"),
line(6018, "jrcgrvp"),
line(276452, "jwpms.snh"),
line(dir, "njv"),
line(173910, "pmshlv"),
line(144465, "qwqstp"),
line(186879, "rqchbwl.mwm"),
line(dir, "vrsdff"),
line(cd, "bqzdswtj"),
line(ls),
line(dir, "jzqcnnw"),
line(dir, "njccj"),
line(cd, "jzqcnnw"),
line(ls),
line(dir, "fwt"),
line(dir, "rgvmcsb"),
line(235477, "ttctlvjp"),
line(cd, "fwt"),
line(ls),
line(20557, "lfnhb.hqz"),
line(cd, ".."),
line(cd, "rgvmcsb"),
line(ls),
line(89387, "snvcfdpf.hvf"),
line(cd, ".."),
line(cd, ".."),
line(cd, "njccj"),
line(ls),
line(262201, "lfnhb"),
line(200215, "ttctlvjp"),
line(232220, "vngjfb.nlm"),
line(cd, ".."),
line(cd, ".."),
line(cd, "njv"),
line(ls),
line(dir, "vrsdff"),
line(cd, "vrsdff"),
line(ls),
line(17060, "nnvjbqgl"),
line(cd, ".."),
line(cd, ".."),
line(cd, "vrsdff"),
line(ls),
line(dir, "bjsmnvpp"),
line(dir, "bsgdhgf"),
line(dir, "pgzj"),
line(dir, "snqqrvwd"),
line(dir, "vwn"),
line(cd, "bjsmnvpp"),
line(ls),
line(172378, "vngjfb.nlm"),
line(cd, ".."),
line(cd, "bsgdhgf"),
line(ls),
line(32538, "dggftf"),
line(cd, ".."),
line(cd, "pgzj"),
line(ls),
line(1788, "gsfqvvws.nsd"),
line(dir, "jrg"),
line(dir, "vrsdff"),
line(cd, "jrg"),
line(ls),
line(116492, "jgbn.zhm"),
line(cd, ".."),
line(cd, "vrsdff"),
line(ls),
line(dir, "tjngdssd"),
line(cd, "tjngdssd"),
line(ls),
line(194563, "snqqrvwd.gmw"),
line(cd, ".."),
line(cd, ".."),
line(cd, ".."),
line(cd, "snqqrvwd"),
line(ls),
line(dir, "dlwn"),
line(103245, "pmshlv"),
line(dir, "pzcl"),
line(163325, "vngjfb.nlm"),
line(40822, "vrsdff.chz"),
line(cd, "dlwn"),
line(ls),
line(dir, "ffhpr"),
line(119317, "hnb.nzj"),
line(cd, "ffhpr"),
line(ls),
line(131380, "bcfwsgs.tzg"),
line(209987, "jgbn.zhm"),
line(286370, "pmshlv"),
line(cd, ".."),
line(cd, ".."),
line(cd, "pzcl"),
line(ls),
line(dir, "mjqww"),
line(cd, "mjqww"),
line(ls),
line(178542, "vrsdff.sqs"),
line(cd, ".."),
line(cd, ".."),
line(cd, ".."),
line(cd, "vwn"),
line(ls),
line(268238, "vrsdff.mcr"),
line(cd, ".."),
line(cd, ".."),
line(cd, ".."),
line(cd, "dvqtdsr"),
line(ls),
line(109637, "gznfwq.tjf"),
line(26909, "jrcgrvp.gzb"),
line(dir, "pqshn"),
line(dir, "qrdwn"),
line(299319, "snqqrvwd.dlq"),
line(191068, "ttctlvjp"),
line(dir, "zgqqb"),
line(32751, "zzgd"),
line(cd, "pqshn"),
line(ls),
line(292725, "sjmctn.ddl"),
line(cd, ".."),
line(cd, "qrdwn"),
line(ls),
line(249329, "fmzdmv"),
line(dir, "jrcgrvp"),
line(dir, "snmsbc"),
line(158902, "vdjjgd.lnb"),
line(cd, "jrcgrvp"),
line(ls),
line(114378, "vdjjgd.lnb"),
line(cd, ".."),
line(cd, "snmsbc"),
line(ls),
line(dir, "ftqwmwh"),
line(64765, "jgbn.zhm"),
line(dir, "qbcs"),
line(cd, "ftqwmwh"),
line(ls),
line(dir, "bnqlv"),
line(cd, "bnqlv"),
line(ls),
line(136350, "cwlmqt.bbh"),
line(dir, "vrsdff"),
line(cd, "vrsdff"),
line(ls),
line(141840, "vngjfb.nlm"),
line(228473, "vrsdff"),
line(cd, ".."),
line(cd, ".."),
line(cd, ".."),
line(cd, "qbcs"),
line(ls),
line(119659, "pmshlv"),
line(cd, ".."),
line(cd, ".."),
line(cd, ".."),
line(cd, "zgqqb"),
line(ls),
line(76559, "jgbn.zhm"),
line(51194, "tfjjcvg.wcz"),
line(182300, "vdjjgd.lnb"),
line(cd, ".."),
line(cd, ".."),
line(cd, "pggh"),
line(ls),
line(dir, "bptq"),
line(141811, "jfggzwlr.qfv"),
line(dir, "mjqww"),
line(280055, "rvgjwv"),
line(47733, "tzvslczc"),
line(cd, "bptq"),
line(ls),
line(142261, "djwzwblq"),
line(dir, "hzm"),
line(171045, "jrcgrvp"),
line(dir, "jzdz"),
line(65989, "pfdm"),
line(cd, "hzm"),
line(ls),
line(dir, "lwzcrrn"),
line(cd, "lwzcrrn"),
line(ls),
line(75543, "rjbvvlns"),
line(cd, ".."),
line(cd, ".."),
line(cd, "jzdz"),
line(ls),
line(29854, "rdjhtht"),
line(cd, ".."),
line(cd, ".."),
line(cd, "mjqww"),
line(ls),
line(76340, "jrcgrvp.ppr"),
line(dir, "lfnhb"),
line(cd, "lfnhb"),
line(ls),
line(244279, "ttctlvjp"),
line(cd, ".."),
line(cd, ".."),
line(cd, ".."),
line(cd, "zlzjmjvn"),
line(ls),
line(116546, "vngjfb.nlm"),
line(cd, ".."),
line(cd, ".."),
line(cd, "wndttgwm"),
line(ls),
line(201916, "pbjrts.vjz"),
line(14494, "swbmqtg"),
line(cd, ".."),
line(cd, ".."),
line(cd, "vhbnn"),
line(ls),
line(dir, "gwj"),
line(dir, "hnsphswl"),
line(dir, "sspz"),
line(dir, "zpgg"),
line(cd, "gwj"),
line(ls),
line(299701, "mghnhljr.tmp"),
line(cd, ".."),
line(cd, "hnsphswl"),
line(ls),
line(dir, "bmpsvbmv"),
line(dir, "ndb"),
line(dir, "pwmfc"),
line(dir, "qrrrt"),
line(cd, "bmpsvbmv"),
line(ls),
line(dir, "hwpndl"),
line(cd, "hwpndl"),
line(ls),
line(2660, "mjqww.bjm"),
line(cd, ".."),
line(cd, ".."),
line(cd, "ndb"),
line(ls),
line(16600, "jqdswj.dvp"),
line(241104, "jscnpf"),
line(32178, "nwgsvh"),
line(cd, ".."),
line(cd, "pwmfc"),
line(ls),
line(16607, "pmshlv"),
line(234937, "ttctlvjp"),
line(127344, "vdjjgd.lnb"),
line(95778, "zgv.src"),
line(dir, "zzvg"),
line(cd, "zzvg"),
line(ls),
line(dir, "blrd"),
line(dir, "fscnr"),
line(147045, "smdlbzl"),
line(107844, "snqqrvwd.gzg"),
line(cd, "blrd"),
line(ls),
line(86042, "lfnhb.hpq"),
line(cd, ".."),
line(cd, "fscnr"),
line(ls),
line(135422, "zpdlcd"),
line(cd, ".."),
line(cd, ".."),
line(cd, ".."),
line(cd, "qrrrt"),
line(ls),
line(5908, "cwwc"),
line(dir, "dgswrljc"),
line(dir, "dlhdg"),
line(5261, "jgbn.zhm"),
line(310282, "pmshlv"),
line(134603, "vngjfb.nlm"),
line(202988, "zcdtsqq.qfv"),
line(cd, "dgswrljc"),
line(ls),
line(40499, "lrttnqm.zbc"),
line(312009, "pmshlv"),
line(cd, ".."),
line(cd, "dlhdg"),
line(ls),
line(66562, "pmshlv"),
line(cd, ".."),
line(cd, ".."),
line(cd, ".."),
line(cd, "sspz"),
line(ls),
line(dir, "dfs"),
line(dir, "gzwlzc"),
line(139140, "vngjfb.nlm"),
line(222854, "vrsdff.bwn"),
line(cd, "dfs"),
line(ls),
line(228281, "jjbrp.mjz"),
line(204654, "nsvv.mjt"),
line(309232, "qwhfjsnt.ptj"),
line(cd, ".."),
line(cd, "gzwlzc"),
line(ls),
line(dir, "bsqbbfgz"),
line(cd, "bsqbbfgz"),
line(ls),
line(14589, "qgtmg.vgr"),
line(cd, ".."),
line(cd, ".."),
line(cd, ".."),
line(cd, "zpgg"),
line(ls),
line(125276, "wfjfpb.wmh")]).

sample([line(cd, "/"),
line(ls),
line(dir, "a"),
line(14848514, "b.txt"),
line(8504156, "c.dat"),
line(dir, "d"),
line(cd, "a"),
line(ls),
line(dir, "e"),
line(29116, "f"),
line(2557, "g"),
line(62596, "h.lst"),
line(cd, "e"),
line(ls),
line(584, "i"),
line(cd, ".."),
line(cd, ".."),
line(cd, "d"),
line(ls),
line(4060174, "j"),
line(8033020, "d.log"),
line(5626152, "d.ext"),
line(7214296, "k")]).
